/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d9e6da",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#29695b",
        "on-secondary-container": "#616a00",
        tertiary: "#253028",
        outline: "#707975",
        "on-surface-variant": "#3f4945",
        "surface-variant": "#d4e5ef",
        "on-background": "#0d1e25",
        background: "#f4faff",
        "surface-container-highest": "#d4e5ef",
        "on-tertiary-fixed": "#131e17",
        "on-secondary-fixed": "#1a1d00",
        primary: "#00342b",
        "on-primary-fixed-variant": "#065043",
        "on-primary-fixed": "#00201a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dded49",
        "on-primary": "#ffffff",
        "tertiary-container": "#3b463e",
        secondary: "#5b6300",
        error: "#ba1a1a",
        "primary-fixed": "#afefdd",
        "inverse-surface": "#23333a",
        "secondary-container": "#dded49",
        "primary-fixed-dim": "#94d3c1",
        "surface-dim": "#cbdde7",
        "on-tertiary-container": "#a7b4a9",
        "on-surface": "#0d1e25",
        "secondary-fixed-dim": "#c1d02c",
        "primary-container": "#004d40",
        "surface-container": "#dff1fb",
        "error-container": "#ffdad6",
        "surface-container-high": "#d9ebf5",
        "surface-bright": "#f4faff",
        "inverse-primary": "#94d3c1",
        "surface-container-low": "#e7f6ff",
        "on-primary-container": "#7ebdac",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#f4faff",
        "tertiary-fixed-dim": "#bdcabe",
        "outline-variant": "#bfc9c4",
        "on-tertiary-fixed-variant": "#3e4a41",
        "on-secondary-fixed-variant": "#444b00",
        "inverse-on-surface": "#e2f3fd",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        unit: "8px",
        "margin-desktop": "40px",
        gutter: "24px",
      },
      fontFamily: {
        h1: ["Inter", "ui-sans-serif", "system-ui"],
        h2: ["Inter", "ui-sans-serif", "system-ui"],
        h3: ["Inter", "ui-sans-serif", "system-ui"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui"],
        "label-sm": ["Inter", "ui-sans-serif", "system-ui"],
        caption: ["Inter", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        h1: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        h2: [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": [
          "14px",
          {
            lineHeight: "1",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      boxShadow: {
        "hero-card": "0 32px 64px -16px rgba(0,52,43,0.15)",
      },
    },
  },
  plugins: [],
}
