export const PATHS = {
  HOME: "/",
  TRAINER_DASHBOARD: "/trainer-dashboard",
  TRAINER_OVERVIEW: "/trainer-dashboard/overview",
  TRAINER_CREATE_SESSION: "/trainer-dashboard/create-session",
  TRAINER_RECURRING_SESSIONS: "/trainer-dashboard/recurring-sessions",
  TRAINER_DASHBOARD_ATTENDANCE: "/trainer-dashboard/attendance",
  TRAINER_PAYMENTS: "/trainer-dashboard/payments",
  TRAINER_WALLET: "/trainer-dashboard/payments/wallet",
  TRAINER_SESSION_EARNINGS: "/trainer-dashboard/payments/session-earnings",
  TRAINER_PAYOUT_REQUEST: "/trainer-dashboard/payments/payout-request",
  TRAINER_ACCOUNT_DETAILS: "/trainer-dashboard/payments/account-details",
  TRAINER_PAYOUT_HISTORY: "/trainer-dashboard/payments/payout-history",
  TRAINER_ATTENDANCE: "/trainer/attendance",
  TRAINER_SESSION_HISTORY: "/trainer/sessions/:sessionId/history",
  LOGIN: "/login",
  SIGNUP: "/signup",
};